### ISSUE TITLE
Highlights Not Working

### ISSUE THREAD

**Issue by danshort** [raindropio/desktop#26]
Per this [help page on Highlights](https://help.raindrop.io/highlights/), I should be able to highlight text on a page and see that highlight in the preview on the Raindrop desktop app. Even in the desktop app I'm not seeing the highlight UI as described on the help pages.

<img width="1494" alt="Screen Shot 2022-03-06 at 10 40 27 PM" src="https://user-images.githubusercontent.com/44993/156969223-47c71bba-6de3-4548-a1ed-d91b569676d5.png">

**Comment by exentrich** [comment]
Unfortunately Highlights not ready yet. You discovered a hidden page :) Give me more time to test everything before release.
You will receive an email when it be ready
