### ISSUE TITLE
MacOS app user agent set to iPhone?

### ISSUE THREAD

**Issue by homostellaris** [raindropio/desktop#4]
Hey guys, firstly, great app, loving it so far and have migrated away from Pinboard for it 👍 

Now onto my issue, yesterday I got an unrecognised sign-in to my Google account from Safari on an iPhone. The only possible cause I could think of (other than I've been hacked) is that I signed into the desktop app around the same time.

Is it possible that the MacOS app is somehow identifying as Safari on an iPhone? I tested logging into my Google Account from my actual Safari installation on my Macbook, setting the user agent to iPhone in the development options, and it did indeed show up in my Google Security dashboard as an iPhone.

I'd be very grateful if you could look into this as it would put my mind at ease about my account being compromised 😅 

Thanks!

**Comment by exentrich** [comment]
Yep you right we have set iPhone user-agent for Google auth flow. It's hacky workaround to fix unsupported user agent error for Electron apps.
We found better solution, so upcoming version will not have such confusion

**Comment by homostellaris** [comment]
Thanks for the reply 👍
