### ISSUE TITLE
Version 5.6.5.0 APPX file not signed with trusted certificate

### ISSUE THREAD

**Issue by SoccerNerd** [raindropio/desktop#45]
Trying to install the windows desktop app without using the Microsoft Store (MS Store blocked by my organization). 

When trying to install using the .appx file I get the following error message: 
"Ask the app developer for a new app package. This one isn't signed with a trusted certificate (0x800B0100)"

![image](https://github.com/raindropio/desktop/assets/61528248/0617eef3-6ccf-46fb-9409-97d9041fddd6)

**Comment by exentrich** [comment]
Please use .exe installer instead
