### ISSUE TITLE
Unable to select upload file on Windows 11 24H2

### ISSUE THREAD

**Issue by A5M1** [raindropio/desktop#49]
The hover fade out time is too fast and clicking the 'down arrow' 
![image](https://github.com/raindropio/desktop/assets/101961638/cc5f9fcb-22b9-4bcc-83cd-2d5f3c4b2421), does nothing it took 4 tries to be able to upload anything.

https://github.com/raindropio/desktop/assets/101961638/618a300f-1514-4aa6-8715-4c8df1acb63f

Osinfo:
![image](https://github.com/raindropio/desktop/assets/101961638/8f073b8b-e4b3-4293-ba6e-091ba03dab24)

**Comment by A5M1** [comment]
after seeing issiues #48 seems to be the same story

**Comment by exentrich** [comment]
Has been fixed in recent updates

**Comment by A5M1** [comment]
@exentrich nice thanks
