### ISSUE TITLE
Desktop Linux app ?

### ISSUE THREAD

**Issue by kissu** [raindropio/desktop#5]
Hi !
I was wondering if you plan to port the desktop app to Linux too. 😄

**Comment by exentrich** [comment]
Definitely! But I'm not sure how to implement auto-updates for Electron on Linux, do you have any ideas?

**Comment by kissu** [comment]
Really no idea on how it works. As far as I know, `snap` packages do auto update. Maybe even `AppImage`s. 🤔

**Comment by siphomateke** [comment]
A desktop Linux app would be greatly appreciated. @exentrich I quickly tried porting the app to Linux and it seems to work quite well with few modifications. You can view the changes I made to do this here https://github.com/siphomateke/desktop/commit/3a08ab40c371944548b726be34beac958288125c.

Here is a screenshot of the app running on Linux. (I also changed it to the beta website for my personal build)
![Screenshot of Raindrop.io running on Kubuntu 20.04](https://user-images.githubusercontent.com/19307714/93906384-697d5100-fcfc-11ea-99b9-fb7db8404e3b.png)

It's not perfect and is still missing things like proper icon size variants, but I was able to get Debs and Flatpaks to build and run using Electron Forge. Regarding auto-updates, I'd like to suggest using Flatpaks via [Flathub](https://flathub.org) as it seems to cover the most Linux distributions with minimal effort from the developer. You can view more about publishing to Flathub here: https://github.com/flathub/flathub/wiki/App-Submission

Also, can I just say huge props for making Raindrop open-source! It's awesome to see developers give back to the community.

**Comment by Albonycal** [comment]
any updates on this?

**Comment by rauldipeas** [comment]
Please, we need a Linux desktop app to integrate special actions on launchers like `krunner`, for example, it will give to us a very fast workflow to work with Raindrop.

**Comment by joshbuker** [comment]
@exentrich Any updates on integrating linux support? It seems like @siphomateke got it working on their fork previously.

**Comment by rauldipeas** [comment]
They have a [secret Linux build](https://github.com/raindropio/desktop/blob/2b075145d7593b405d529972d7ec297088627250/build/config.js#L90)...

But, _snap_ it's not the best approach for this, I think.

I prefer traditional _deb_ or _AppImage_ format.

**Comment by exentrich** [comment]
🎉 Linux App now available in Snap Store:
https://snapcraft.io/raindrop

**WARNING: PLEASE CLICK SIGN IN MULTIPLE TIMES to actually sign in!**
Issue will be fixed in future updates.

Not sure about other distribution formats (AppImage, deb, etc). Does they really makes sense in 2022 for Linux users?

**Comment by siphomateke** [comment]
Awesome! Look forward to trying it out.

Regarding other distribution formats, yes, they are still very much relevant. What I originally said pretty much still stands in my opinion, with Flatpak being the most widely supported and loved with minimal effort from the developer. Snap is somewhat divisive among Linux users, AppImages are great but don't support auto-updating and debs require a PPA for auto-updates and are only supported on Debian-based distributions.

If possible, it would be great to support Snap, Flatpak, AppImage and debs, but if you had to choose, I'd suggest at least adding Flatpak support and uploading to Flathub.

**Comment by rauldipeas** [comment]
I'll convert this snap into deb to install here, it's annoying job, but I prefer to do this way.

Anyway, thanks for the Linux support.

**Comment by joshbuker** [comment]
Awesome, thank you!
