### ISSUE TITLE
Icon of Raindrop for Windows, has a background problem

### ISSUE THREAD

**Issue by oeloo** [raindropio/desktop#50]
Hi, Raindrop for Windows icon on Windows task bar has no transparent background. As you can see all the other application icons have a transparent background:
![image](https://github.com/raindropio/desktop/assets/98819304/6dcc254c-18a6-44f0-a55f-abcd29c26951)

**Comment by exentrich** [comment]
Sorry about that, update with fix published to Windows Store. Will be available soon

**Comment by oeloo** [comment]
Well done, I confirm it is now fixed.
