### ISSUE TITLE
Cannot open all Bookmarks in one click

### ISSUE THREAD

**Issue by dnet890** [raindropio/desktop#52]
Hi
I have one folder that contains 87 Bookmarks. But, When I clicked to open all of them on the extension or app. it does not opened all of the links unlike the native bookmark manager from browsers

**Comment by exentrich** [comment]
You probably missed instruction how to fix this that appear right after you try to open multiple bookmarks at once.
https://help.raindrop.io/troubleshooting/open-multiple-links

**Comment by dnet890** [comment]
@exentrich if you mean this option on chrome. it does not worked and it only open 40 tabs unlike the native browsers. What do you think?

<img width="463" alt="image" src="https://github.com/user-attachments/assets/638cca65-7071-46c6-80c8-dd9ab2fbeb82">

**Comment by exentrich** [comment]
I apologize for the confusion; I see the issue you’re experiencing now. 
To open every bookmark in a folder, please go to the folder and scroll down until all bookmarks are fully loaded. Once they are visible, click “Open all bookmarks.”

**Comment by dnet890** [comment]
@exentrich yeah that works. But, Is it possible to make it faster to open all bookmarks at once like the native bookmarks manager on the web browser without scrolling or previewing all the bookmarks at the end?

**Comment by dnet890** [comment]
@exentrich Sorry for multiple response. I checked the desktop snap app. Yes, It can open multiple tabs. But, the tab order for opened links from left to right is not properly correct compared to browser extension. What do you think?
