### ISSUE TITLE
MacOS app hangs upon start

### ISSUE THREAD

**Issue by riddla** [raindropio/desktop#8]
![Screenshot 2020-10-14 at 10 37 19](https://user-images.githubusercontent.com/174157/95964606-4a5c7580-0e09-11eb-939f-7caa233393eb.png)

First start, but nothing happens. The spinner spins on forever.

I'm on Catalina `10.15.7 (19H2)` using your `5.2.42` version.

**Comment by exentrich** [comment]
Sorry about that. `5.2.42` version is corrupted, please update to latest
