### ISSUE TITLE
Is there a support site? How to report problems?

### ISSUE THREAD

**Issue by adriatic** [raindropio/desktop#9]
Just bought a year-long subscription and it took me a while to grasp how to use this tool on my Windows desktop. The key question is the user authentication: it could be done via authentication to the browser as well as authentication directly to the extension running in the browser. In my case, I did not want the browser "know who am i", as the browser does some unwanted actions on my behalf in some situations. I was authenticated to the raindrop extension, but that in itself was not sufficient to get the "stylized cloud icon" to appear on the browser's bar

![image](https://user-images.githubusercontent.com/2712405/98017238-f839bf00-1dcc-11eb-99bf-e739618478e4.png)

I had to click on the Pin icon in order to ensure that the "stylized cloud icon" to **appear and stay** on the browser's bar

![image](https://user-images.githubusercontent.com/2712405/98017812-c37a3780-1dcd-11eb-89c4-7f0f78b151a1.png)

I do not believe that I am the only dumb user who needed this information presented on you on-line documentation, so please add that for the sake of all other newcomers.

I am using Toby as the bookmark manager, but is seems that I will soon switch to raindrop.

Great tool Rustem

**Comment by exentrich** [comment]
Thank you for detailed feedback!
Yes in latest Chrome versions new extensions are not visible by default. This is true for any extension.
When you install an extension Chrome shows a tip how to enable it, you just probably missed it.
I definetely add this info in install process extension screen.

If you have any other problems feel free to send them to info@raindrop.io
